package gregtech.loaders.recipe;

import gregtech.api.recipes.RecipeMaps;
import gregtech.api.unification.OreDictUnifier;
import gregtech.common.items.MetaItems;

import static gregtech.api.unification.material.Materials.*;
import static gregtech.api.unification.ore.OrePrefix.*;

public final class GCYMMiscRecipes {

    private GCYMMiscRecipes() {}

    public static void init() {
        grapheneRecipes();
    }

    /**
     * Recipes for graphene that don't get autogenerated
     */
    private static void grapheneRecipes() {
        if (OreDictUnifier.get(foil, Graphene, 4).isEmpty()) {
            return;
        }

        // Foil Extruding
        RecipeMaps.EXTRUDER_RECIPES.recipeBuilder()
                .input(dust, Graphene)
                .notConsumable(MetaItems.SHAPE_EXTRUDER_FOIL)
                .output(foil, Graphene, 4)
                .duration((int) Graphene.getMass())
                .EUt(24)
                .buildAndRegister();
    }
}
