package gregtech.common.pipelike.fluidpipe.net;

import gregtech.common.ConfigHolder;

import net.minecraft.nbt.NBTTagCompound;

/**
 * Tracks pressure state for a single fluid pipe node.
 * Pressure is measured in milliBar (mBar). Ambient pressure is 0 mBar.
 */
public class FluidPressureData {

    private int pressureMilliBar;
    private int siphonPressure = 0;  // Pressure generated by siphon effect
    private int burstCountdown = -1;
    private int cachedResistance = -1;

    public FluidPressureData() {
        this.pressureMilliBar = 0;
    }

    public int getPressure() {
        return pressureMilliBar;
    }

    public void setPressure(int pressureMilliBar) {
        this.pressureMilliBar = pressureMilliBar;
    }

    public int getSiphonPressure() {
        return siphonPressure;
    }

    public void setSiphonPressure(int pressure) {
        this.siphonPressure = Math.max(0, pressure);
    }

    public void addPressure(int amount) {
        this.pressureMilliBar += amount;
    }

    /**
     * Compute the resistance for flow through this node.
     * Resistance = fluid viscosity factor + pipe friction constant.
     * Cached and only recomputed when invalidated.
     */
    public int getResistance(int pipeFriction, int fluidViscosity) {
        if (cachedResistance < 0) {
            cachedResistance = Math.max(1, pipeFriction + fluidViscosity / 100);
        }
        return cachedResistance;
    }

    public void invalidateResistanceCache() {
        cachedResistance = -1;
    }

    /**
     * @return true if the pipe has ruptured (countdown reached 0)
     */
    public boolean tickBurst(int currentPressure, int burstRating) {
        if (currentPressure > burstRating) {
            if (burstCountdown < 0) {
                burstCountdown = ConfigHolder.machines.pressure.burstCountdown;
            } else {
                burstCountdown--;
            }
            return burstCountdown <= 0;
        } else {
            // Pressure dropped below burst, reset countdown
            if (burstCountdown > 0) {
                burstCountdown = -1;
            }
            return false;
        }
    }

    public int getBurstCountdown() {
        return burstCountdown;
    }

    public boolean isOverpressured(int burstRating) {
        return pressureMilliBar > burstRating;
    }

    /**
     * Calculate effective pressure delta between this node and a neighbor.
     * Accounts for gravity: positive heightDiff means neighbor is above us (costs pressure).
     */
    public int getEffectiveDelta(FluidPressureData neighbor, int heightDiff) {
        int rawDelta = this.pressureMilliBar - neighbor.pressureMilliBar;
        int gravityPenalty = heightDiff * ConfigHolder.machines.pressure.gravityPenaltyPerBlock;
        return rawDelta - gravityPenalty;
    }

    /**
     * Calculate flow rate from effective delta and resistance using pure integer math.
     * flow = (effectiveDelta * baseScalar) / resistance
     */
    public static int calculateFlow(int effectiveDelta, int resistance) {
        if (effectiveDelta <= ConfigHolder.machines.pressure.minimumFlowThreshold) {
            return 0;
        }
        long flow = ((long) effectiveDelta * ConfigHolder.machines.pressure.flowBaseScalar) / Math.max(1, resistance);
        return (int) Math.min(flow, ConfigHolder.machines.pressure.maxFlowPerTick);
    }

    public NBTTagCompound serializeNBT() {
        NBTTagCompound tag = new NBTTagCompound();
        tag.setInteger("Pressure", pressureMilliBar);
        if (siphonPressure > 0) {
            tag.setInteger("SiphonPressure", siphonPressure);
        }
        if (burstCountdown >= 0) {
            tag.setInteger("BurstCountdown", burstCountdown);
        }
        return tag;
    }

    public void deserializeNBT(NBTTagCompound tag) {
        pressureMilliBar = tag.getInteger("Pressure");
        siphonPressure = tag.hasKey("SiphonPressure") ? tag.getInteger("SiphonPressure") : 0;
        burstCountdown = tag.hasKey("BurstCountdown") ? tag.getInteger("BurstCountdown") : -1;
    }
}
