package gregtech.api.items.toolitem;

public enum ToolOreDict {
    toolSword,
    toolPickaxe,
    toolShovel,
    toolAxe,
    toolHoe,
    toolSaw,
    toolHammer,
    toolMallet,
    toolMiningHammer,
    toolSpade,
    toolWrench,
    toolFile,
    toolCrowbar,
    toolScrewdriver,
    toolMortar,
    toolWireCutter,
    toolScythe,
    toolKnife,
    toolButcheryKnife,
    toolDrill,
    toolChainsaw,
    toolBuzzsaw,
    toolPlunger,
    toolScissors,

    // GT6 ported tools
    toolDoubleAxe,
    toolChisel,
    toolClub,
    toolConstructionPickaxe,
    toolPlow,
    toolUniversalSpade,
    toolBendingCylinder,
    toolBendingCylinderSmall,
    toolRollingPin,
    toolMagnifyingGlass,
    toolMonkeyWrench,
    toolPincers,
    toolFlintAndTinder,
    toolJackhammer,
}
